#!/bin/bash
set -e
set -x

dir="$1"

echo $(tty) > $1/temp_for_gdb
echo $$ > $1/pid_of_gterm

(
stty isig brkint susp ''
while true; do sleep 3600; done </dev/null
)

#(
#s="$(stty -g)"
#exec 3<&0
#trap 'stty "$s" 0<&3;exit' 0 INT QUIT
#cat <<EOM
#    In some other terminal, run the command
#    cat <$(tty)
#    Press ^C or ^\ to quit.
#EOM
#stty raw isig brkint susp ''
#while true; do sleep 3600; done </dev/null
#)



